// Quiz action types
export const FETCH_QUIZ_REQUEST = "FETCH_QUIZ_REQUEST";
export const FETCH_QUIZ_SUCCESS = "FETCH_QUIZ_SUCCESS";
export const FETCH_QUIZ_FAILURE = "FETCH_QUIZ_FAILURE";

export const SUBMIT_QUIZ_REQUEST = "SUBMIT_QUIZ_REQUEST";
export const SUBMIT_QUIZ_SUCCESS = "SUBMIT_QUIZ_SUCCESS";
export const SUBMIT_QUIZ_FAILURE = "SUBMIT_QUIZ_FAILURE";

export const RESET_QUIZ = "RESET_QUIZ";
export const SET_QUIZ_ANSWERS = "SET_QUIZ_ANSWERS";
