// Certificate action types
export const FETCH_CERTIFICATES_REQUEST = "FETCH_CERTIFICATES_REQUEST";
export const FETCH_CERTIFICATES_SUCCESS = "FETCH_CERTIFICATES_SUCCESS";
export const FETCH_CERTIFICATES_FAILURE = "FETCH_CERTIFICATES_FAILURE";

export const GENERATE_CERTIFICATE_REQUEST = "GENERATE_CERTIFICATE_REQUEST";
export const GENERATE_CERTIFICATE_SUCCESS = "GENERATE_CERTIFICATE_SUCCESS";
export const GENERATE_CERTIFICATE_FAILURE = "GENERATE_CERTIFICATE_FAILURE";

export const DOWNLOAD_CERTIFICATE_REQUEST = "DOWNLOAD_CERTIFICATE_REQUEST";
export const DOWNLOAD_CERTIFICATE_SUCCESS = "DOWNLOAD_CERTIFICATE_SUCCESS";
export const DOWNLOAD_CERTIFICATE_FAILURE = "DOWNLOAD_CERTIFICATE_FAILURE";

export const RESET_CERTIFICATES = "RESET_CERTIFICATES";
